/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Jan 27, 2014, 5:58:37 PM
 */

package smartattendancesystem;
import smartattendancesystem.bean.UsermasterBean;
//import smartattendancesystem.report.*;
import smartattendancesystem.bean.DBOperations;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;
/**
 *
 * @author Rajesh
 */
public class MainFrame extends javax.swing.JFrame {
    UsermasterBean objUsermasterBean;
    static int userId;
    static String userType;
    int userActivityID,s;
    /** Creates new form MainFrame */
    public MainFrame()
    {
    }
    public MainFrame(UsermasterBean objUsermasterBean, int userActivityID) {
        initComponents();

        GraphicsEnvironment e = GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(e.getMaximumWindowBounds());
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);

        this.objUsermasterBean = objUsermasterBean;
        this.userActivityID = userActivityID;

        userId = objUsermasterBean.getUserId();
        userType = objUsermasterBean.getUserType();
        if (userType.equalsIgnoreCase("employee")) {

            mbMainFrame.remove(mnuUserMaintenance);
           // mbMainFrame.remove(mnuReports);
         // mnuLoanMaintenance.remove(miLoanIssueDetail);
        }
    }
public static void myfun2(int x,String p,String q,String y)
{
   /* LoanIssueDetail objLID = new LoanIssueDetail(x,p,q,y);
    objLID.pack();
    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension jInternalFrameSize =  objLID.getSize();
    objLID.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
    jDesktopPane1.add(objLID);
    objLID.setVisible(true);
    */
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        mbMainFrame = new javax.swing.JMenuBar();
        mnuProfile = new javax.swing.JMenu();
        miProfileAccountDetail = new javax.swing.JMenuItem();
        miProfilePersonalDetail = new javax.swing.JMenuItem();
        mnuUserMaintenance = new javax.swing.JMenu();
        miUserAccountDetail = new javax.swing.JMenuItem();
        miUserPersonalDetail = new javax.swing.JMenuItem();
        mnuClientMaintenance = new javax.swing.JMenu();
        miClientPersonalDetail = new javax.swing.JMenuItem();
        mnuLoanMaintenance = new javax.swing.JMenu();
        miLoanPlanDetail = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                window_closed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDesktopPane1.add(jOptionPane1);
        jOptionPane1.setBounds(120, 710, 10, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background1.jpg"))); // NOI18N
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(0, -80, 1370, 840);

        mnuProfile.setForeground(new java.awt.Color(0, 0, 102));
        mnuProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_prof.png"))); // NOI18N
        mnuProfile.setText("FACULTY PROFILE");
        mnuProfile.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N

        miProfileAccountDetail.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        miProfileAccountDetail.setForeground(new java.awt.Color(0, 102, 204));
        miProfileAccountDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bullet_triangle_blue.png"))); // NOI18N
        miProfileAccountDetail.setText("Profile Account Detail");
        miProfileAccountDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miProfileAccountDetailMouseClicked(evt);
            }
        });
        miProfileAccountDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfileAccountDetailActionPerformed(evt);
            }
        });
        mnuProfile.add(miProfileAccountDetail);

        miProfilePersonalDetail.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        miProfilePersonalDetail.setForeground(new java.awt.Color(0, 102, 204));
        miProfilePersonalDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bullet_triangle_blue.png"))); // NOI18N
        miProfilePersonalDetail.setText("Profile Personal Detail");
        miProfilePersonalDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfilePersonalDetailActionPerformed(evt);
            }
        });
        mnuProfile.add(miProfilePersonalDetail);

        mbMainFrame.add(mnuProfile);

        mnuUserMaintenance.setForeground(new java.awt.Color(0, 0, 102));
        mnuUserMaintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_maint.png"))); // NOI18N
        mnuUserMaintenance.setText("ADMIN MANAGER");
        mnuUserMaintenance.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N

        miUserAccountDetail.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        miUserAccountDetail.setForeground(new java.awt.Color(0, 102, 204));
        miUserAccountDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bullet_triangle_blue.png"))); // NOI18N
        miUserAccountDetail.setText("User Account Detail");
        miUserAccountDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserAccountDetailActionPerformed(evt);
            }
        });
        mnuUserMaintenance.add(miUserAccountDetail);

        miUserPersonalDetail.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        miUserPersonalDetail.setForeground(new java.awt.Color(0, 102, 204));
        miUserPersonalDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bullet_triangle_blue.png"))); // NOI18N
        miUserPersonalDetail.setText("User Personal Detail");
        miUserPersonalDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserPersonalDetailActionPerformed(evt);
            }
        });
        mnuUserMaintenance.add(miUserPersonalDetail);

        mbMainFrame.add(mnuUserMaintenance);

        mnuClientMaintenance.setForeground(new java.awt.Color(0, 0, 102));
        mnuClientMaintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/client_maint.png"))); // NOI18N
        mnuClientMaintenance.setText("STUDENT DET.");
        mnuClientMaintenance.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N

        miClientPersonalDetail.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        miClientPersonalDetail.setForeground(new java.awt.Color(0, 102, 204));
        miClientPersonalDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bullet_triangle_blue.png"))); // NOI18N
        miClientPersonalDetail.setText("Student Registeration");
        miClientPersonalDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClientPersonalDetailActionPerformed(evt);
            }
        });
        mnuClientMaintenance.add(miClientPersonalDetail);

        mbMainFrame.add(mnuClientMaintenance);

        mnuLoanMaintenance.setForeground(new java.awt.Color(0, 0, 102));
        mnuLoanMaintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loan_mgr.jpg"))); // NOI18N
        mnuLoanMaintenance.setText("ATTENDANCE DET.");
        mnuLoanMaintenance.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N

        miLoanPlanDetail.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        miLoanPlanDetail.setForeground(new java.awt.Color(0, 102, 204));
        miLoanPlanDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bullet_triangle_blue.png"))); // NOI18N
        miLoanPlanDetail.setText("Attendance Operation");
        miLoanPlanDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLoanPlanDetailActionPerformed(evt);
            }
        });
        mnuLoanMaintenance.add(miLoanPlanDetail);

        mbMainFrame.add(mnuLoanMaintenance);

        jMenu1.setForeground(new java.awt.Color(0, 0, 102));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jMenu1.setText("EXIT");
        jMenu1.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        mbMainFrame.add(jMenu1);

        setJMenuBar(mbMainFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miProfileAccountDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miProfileAccountDetailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_miProfileAccountDetailMouseClicked

    private void miProfileAccountDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfileAccountDetailActionPerformed
        // TODO add your handling code here:
        ProfileAccountDetail objUserAccountDetail =new ProfileAccountDetail();
        objUserAccountDetail.pack();
        //usefull part for you.. if open shows, if not creates new one
        if (jDesktopPane1.getSelectedFrame() != null)
        {
            jOptionPane1.showMessageDialog(this, "First close the opened window...?", "ERROR", jOptionPane1.ERROR_MESSAGE);
        }   
        else
        {
             Dimension desktopSize = jDesktopPane1.getSize();
             Dimension jInternalFrameSize = objUserAccountDetail.getSize();
             objUserAccountDetail.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
             jDesktopPane1.add(objUserAccountDetail);
             objUserAccountDetail.setVisible(true);
        }
    }//GEN-LAST:event_miProfileAccountDetailActionPerformed

    private void miProfilePersonalDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfilePersonalDetailActionPerformed
        // TODO add your handling code here:
        ProfilePersonalDetail objProfilePersonalDetail =new ProfilePersonalDetail();
        objProfilePersonalDetail.pack();
        //usefull part for you.. if open shows, if not creates new one
        if (jDesktopPane1.getSelectedFrame() != null)
        {
            jOptionPane1.showMessageDialog(this, "First close the opened window...?", "ERROR", jOptionPane1.ERROR_MESSAGE);
        }
        else
        {
             Dimension desktopSize = jDesktopPane1.getSize();
             Dimension jInternalFrameSize = objProfilePersonalDetail.getSize();
             objProfilePersonalDetail.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
             jDesktopPane1.add(objProfilePersonalDetail);
             objProfilePersonalDetail.setVisible(true);
        }
}//GEN-LAST:event_miProfilePersonalDetailActionPerformed

    private void miUserAccountDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserAccountDetailActionPerformed
        // TODO add your handling code here:
        UserAccountDetail objUserAccountDetail = new  UserAccountDetail();
        objUserAccountDetail.pack();
        //usefull part for you.. if open shows, if not creates new one
        if (jDesktopPane1.getSelectedFrame() != null)
        {
            jOptionPane1.showMessageDialog(this, "First close the opened window...?", "ERROR", jOptionPane1.ERROR_MESSAGE);
        }
        else
        {
             Dimension desktopSize = jDesktopPane1.getSize();
             Dimension jInternalFrameSize = objUserAccountDetail.getSize();
             objUserAccountDetail.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
             jDesktopPane1.add(objUserAccountDetail);
             objUserAccountDetail.setVisible(true);
        }
}//GEN-LAST:event_miUserAccountDetailActionPerformed

    private void miUserPersonalDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserPersonalDetailActionPerformed
        // TODO add your handling code here:
        UserPersonalDetail objUserPersonalDetail = new  UserPersonalDetail();
        objUserPersonalDetail.pack();
        //usefull part for you.. if open shows, if not creates new one
        if (jDesktopPane1.getSelectedFrame() != null)
        {
            jOptionPane1.showMessageDialog(this, "First close the opened window...?", "ERROR", jOptionPane1.ERROR_MESSAGE);
        }
        else
        {
             Dimension desktopSize = jDesktopPane1.getSize();
             Dimension jInternalFrameSize = objUserPersonalDetail.getSize();
             objUserPersonalDetail.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
             jDesktopPane1.add(objUserPersonalDetail);
             objUserPersonalDetail.setVisible(true);
        }
}//GEN-LAST:event_miUserPersonalDetailActionPerformed

    private void miLoanPlanDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLoanPlanDetailActionPerformed
       // TODO add your handling code here:
        AttendanceDetail objLoanPlanDetail = new AttendanceDetail();
        objLoanPlanDetail.pack();
        //usefull part for you.. if open shows, if not creates new one
        if (jDesktopPane1.getSelectedFrame() != null)
        {
            jOptionPane1.showMessageDialog(this, "First close the opened window...?", "ERROR", jOptionPane1.ERROR_MESSAGE);
        }
        else
        {
             Dimension desktopSize = jDesktopPane1.getSize();
             Dimension jInternalFrameSize =  objLoanPlanDetail.getSize();
             objLoanPlanDetail.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
             jDesktopPane1.add( objLoanPlanDetail);
             objLoanPlanDetail.setVisible(true);
        }
}//GEN-LAST:event_miLoanPlanDetailActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        s=jOptionPane1.showConfirmDialog(null,"Do you really want to exit ?","Confirm exit",jOptionPane1.YES_NO_OPTION,jOptionPane1.QUESTION_MESSAGE,null);
        if(s==0) {
            logout();
        }
}//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        logout();
}//GEN-LAST:event_jMenu1ActionPerformed

    private void window_closed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_window_closed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_window_closed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        s=jOptionPane1.showConfirmDialog(null,"Do you really want to exit ?","Confirm exit",jOptionPane1.YES_NO_OPTION,jOptionPane1.QUESTION_MESSAGE,null);
        if(s==0) {
            logout();
        }
    }//GEN-LAST:event_formWindowClosing

    private void miClientPersonalDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClientPersonalDetailActionPerformed
        // TODO add your handling code here:
        StudentAccountDetail objStudentAccountDetail = new  StudentAccountDetail();
        objStudentAccountDetail.pack();
        //usefull part for you.. if open shows, if not creates new one
        if (jDesktopPane1.getSelectedFrame() != null)
        {
            jOptionPane1.showMessageDialog(this, "First close the opened window...?", "ERROR", jOptionPane1.ERROR_MESSAGE);
        }
        else
        {
            Dimension desktopSize = jDesktopPane1.getSize();
            Dimension jInternalFrameSize =  objStudentAccountDetail.getSize();
            objStudentAccountDetail.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
            jDesktopPane1.add( objStudentAccountDetail);
            objStudentAccountDetail.setVisible(true);
        }
    }//GEN-LAST:event_miClientPersonalDetailActionPerformed
 void logout() {
        DBOperations objDB = new DBOperations();
        objDB.updateUserActivity(userActivityID);
        System.exit(0);

    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JMenuBar mbMainFrame;
    private javax.swing.JMenuItem miClientPersonalDetail;
    private javax.swing.JMenuItem miLoanPlanDetail;
    private javax.swing.JMenuItem miProfileAccountDetail;
    private javax.swing.JMenuItem miProfilePersonalDetail;
    private javax.swing.JMenuItem miUserAccountDetail;
    private javax.swing.JMenuItem miUserPersonalDetail;
    private javax.swing.JMenu mnuClientMaintenance;
    private javax.swing.JMenu mnuLoanMaintenance;
    private javax.swing.JMenu mnuProfile;
    private javax.swing.JMenu mnuUserMaintenance;
    // End of variables declaration//GEN-END:variables

}
